### ISSUE TITLE
Create Model Files

### ISSUE THREAD

**Issue by devansh-299** [devansh-299/LunchBox#1]
### Description
Create data model files for:
* Restraunts [_use [this link](https://developers.zomato.com/documentation#!/restaurant/restaurant_0) for definition_]
* Reviews [_use [this link](https://developers.zomato.com/documentation#!/restaurant/reviews) for definition_]

### Screenshot/Recording
_NA_

**Comment by epicadk** [comment]
I'd like to work on this

**Comment by devansh-299** [comment]
Sure! go ahead

**Comment by epicadk** [comment]
PR submitted

**Comment by devansh-299** [comment]
Solved by #2
