### ISSUE TITLE
Search Response not proper 

### ISSUE THREAD

**Issue by epicadk** [devansh-299/LunchBox#22]
### Description

Search Response is not working

**Comment by epicadk** [comment]
I'd like to solve this

**Comment by devansh-299** [comment]
@epicadk can you describe the issue?

**Comment by epicadk** [comment]
basically with the response model we have currently I tried making a retrofit request. The response was okay (Checked using httploggerinterceptor) however it was not de-serialized properly. PR has already been sent for the fix.
