### ISSUE TITLE
Add Restaurant Details Screen

### ISSUE THREAD

**Issue by devansh-299** [devansh-299/LunchBox#39]
### Description
Currently, we have the `recyclerview` to display restaurants but nothing happens when clicking on a restaurant item. The idea is to direct users to that specific restaurant's details when clicking on the item. 

* _API Documentation_: [link](https://developers.zomato.com/documentation#!/restaurant/) 
* Also, please describe your approach (design) before sending a pull request

**Comment by epicadk** [comment]
Do you think we should make the restaurant class parcelable or make another request to the API to the restaurant endpoint ?

**Comment by devansh-299** [comment]
In my opinion, the `parcelable` approach seems the way to go 🤔 . 
What do you think?

**Comment by epicadk** [comment]
Hmm I think if we can however in the geocode endpoint there are no highlights so if we want to display them we'll have to make a request.

**Comment by epicadk** [comment]
Also if we do have to do this should we convert the models to kotlin to make it easier or should we implement it in java itself?

**Comment by devansh-299** [comment]
For now, let's continue with Java. Later, as planned we will shift to Kotlin.

**Comment by epicadk** [comment]
Can I work on this?

**Comment by devansh-299** [comment]
Sure, go ahead
