### ISSUE TITLE
Add Category Filters and Markers in Home Fragment

### ISSUE THREAD

**Issue by devansh-299** [devansh-299/LunchBox#40]
### Description
Restaurants can be filtered on the basis of categories. In `HomeFragment`, users should be able to filter and distinguish restaurants catergory wise. For this,  **map markers** and **chips** (to filter restaurants) can be used. 
- For _map markers_  refer [this page](https://developers.google.com/maps/documentation/android-sdk/marker)
- For chips, we can use something like this
![Screenshot from 2020-10-06 23-43-21](https://user-images.githubusercontent.com/46667021/95243143-d11fba00-082d-11eb-8691-62adc20e82bf.png)

**Comment by unc0ded** [comment]
I can take this up.

**Comment by devansh-299** [comment]
> 
> 
> I can take this up.

Ok, go ahead!

**Comment by epicadk** [comment]
> I can take this up.

If you have not started can you fork #38 and start working from there. I think there will be a conflict otherwise.

**Comment by devansh-299** [comment]
@epicadk there are minor linting issues in #38, if you can fix them then I will merge the pull request right ahead

**Comment by unc0ded** [comment]
There seems to be some limitation in the Zomato API regarding category filters, it can take only one category at a time, not a comma separated string of category ids. How do you want to proceed? @devansh-299

**Comment by devansh-299** [comment]
> 
> 
> There seems to be some limitation in the Zomato API regarding category filters, it can take only one category at a time, not a comma separated string of category ids. How do you want to proceed? @devansh-299

@unc0ded 
We can send different API requests for each category and merge the results but I am not much confident about this. You will need to chain multiple API calls for this.
What do you think about this approach?

**Comment by epicadk** [comment]
> There seems to be some limitation in the Zomato API regarding category filters, it can take only one category at a time, not a comma separated string of category ids. How do you want to proceed? @devansh-299

csv works for me.

**Comment by unc0ded** [comment]
> @unc0ded
> We can send different API requests for each category and merge the results but I am not much confident about this. You will need to chain multiple API calls for this.
> What do you think about this approach?

It's certainly doable, but it'll require some more logic to remove duplicate entries, if any. @devansh-299 



> csv works for me.

You sure? Only the cuisines endpoint accepts comma separated ids, according to what I tested. @epicadk

**Comment by unc0ded** [comment]
I have the single filter part ready, we need to finalize on this.

**Comment by epicadk** [comment]
> > @unc0ded
> > We can send different API requests for each category and merge the results but I am not much confident about this. You will need to chain multiple API calls for this.
> > What do you think about this approach?
> 
> It's certainly doable, but it'll require some more logic to remove duplicate entries, if any. @devansh-299 
> 
> 
> 
> > csv works for me.
> 
> You sure? Only the cuisines endpoint accepts comma separated ids, according to what I tested. @epicadk 

Nope even works on the search endpoint

**Comment by unc0ded** [comment]
> 
> Nope even works on the search endpoint

Apologies for not being clear enough. I'm saying that the search endpoint doesn't filter the restaurants if you enter more than one category id. Check the 'results_found' entry. @epicadk

**Comment by devansh-299** [comment]
> 
> 
> > Nope even works on the search endpoint
> 
> Apologies for not being clear enough. I'm saying that the search endpoint doesn't filter the restaurants if you enter more than one category id. Check the 'results_found' entry. @epicadk

@unc0ded its working for me. I used comma separated category_id(s) and it gave different results

**Comment by unc0ded** [comment]
@devansh-299 
**With comma separated category filters:** 
![Screenshot (698)_LI](https://user-images.githubusercontent.com/56927116/96339445-5ae34900-10b2-11eb-947e-44227d796a86.jpg)


**Without any filter:**


![Screenshot (697)_LI](https://user-images.githubusercontent.com/56927116/96339447-5d45a300-10b2-11eb-84e7-c9f920d72a94.jpg)

**Comment by devansh-299** [comment]
> 
> 
> @devansh-299
> **With comma separated category filters:**
> ![Screenshot (698)_LI](https://user-images.githubusercontent.com/56927116/96339445-5ae34900-10b2-11eb-947e-44227d796a86.jpg)
> 
> **Without any filter:**
> 
> ![Screenshot (697)_LI](https://user-images.githubusercontent.com/56927116/96339447-5d45a300-10b2-11eb-84e7-c9f920d72a94.jpg)

For my combination of inputs, passing comma separated ids worked!
 #49's single filter approach also seems good, so if needed we will deal with this later

**Comment by unc0ded** [comment]
> 
> For my combination of inputs, passing comma separated ids worked!
> #49's single filter approach also seems good, so if needed we will deal with this later

Well then I'm at a loss of words 😂 I tried many combinations and it just returned the same number of results as when no category filter is applied.

**Comment by devansh-299** [comment]
> 
> 
> > For my combination of inputs, passing comma separated ids worked!
> > #49's single filter approach also seems good, so if needed we will deal with this later
> 
> Well then I'm at a loss of words 😂 I tried many combinations and it just returned the same number of results as when no category filter is applied.

yeah saw that, try specifying `entity_type` and `entity_id`. 
My combination was city = Kolkata and tried for categories 1 and 1,2 which gave different results.

**Comment by unc0ded** [comment]
> 
> yeah saw that, try specifying `entity_type` and `entity_id`.
> My combination was city = Kolkata and tried for categories 1 and 1,2 which gave different results.

Hmm I actually only tried with the lat, long. Should try with `entity_id` I guess.
