### ISSUE TITLE
Feature : Set Iconified by default to false 

### ISSUE THREAD

**Issue by epicadk** [devansh-299/LunchBox#42]
### Description

Currently in the Search fragment the Search View is brought into focus only when we tap on the icon. 

If we add iconifiedbydefault and set it to false in the Layout file then no matter where the user clicks the search view will be brought to focus

**Comment by devansh-299** [comment]
@epicadk do you want to work on this issue?

**Comment by epicadk** [comment]
No please mark as good first issue @devansh-299

**Comment by maharishi-01** [comment]
can i work on it?

**Comment by devansh-299** [comment]
Sure! go ahead
