### ISSUE TITLE
Add Placeholder Image

### ISSUE THREAD

**Issue by devansh-299** [devansh-299/LunchBox#46]
### Description
For a few restaurants, the images are not available. In such cases, we must have a placeholder image.
For Glide documentation, you can use [this](https://bumptech.github.io/glide/doc/placeholders.html).

### Screenshot

<img src="https://user-images.githubusercontent.com/46667021/95767896-1b43e800-0cd3-11eb-8e3f-c10823a2f5d0.jpg" height="400" width="250" />

**Comment by Xeitor** [comment]
Hello, I would like to work on this issue...

**Comment by devansh-299** [comment]
@Xeitor sure! please go ahead

**Comment by devansh-299** [comment]
@Xeitor are you still working on this issue?

**Comment by Xeitor** [comment]
Hey, sorry for the delay. Has troubles setting up the project. I think maybe today I can send the pr.

**Comment by Xeitor** [comment]
Sorry, could not manage to figure it out.

**Comment by devansh-299** [comment]
> Sorry, could not manage to figure it out.

No problem, you can try learning about [Glide](https://bumptech.github.io/glide/) and about the placeholders that I mentioned in the issue itself and maybe pick up this issue later if available. 

For now, I am unassigning you this issue

**Comment by skiiaA** [comment]
@devansh-299 anybody working on this issue?

**Comment by epicadk** [comment]
> @devansh-299 anybody working on this issue?

No you can work on it.

**Comment by skiiaA** [comment]
fine, I am working on it

**Comment by devansh-299** [comment]
any updates @skiiaA ?

**Comment by shreyashcode** [comment]
@skiiaA are you working on it? I'm willing to fix it.

**Comment by devansh-299** [comment]
> 
> 
> @skiiaA are you working on it? I'm willing to fix it.

@shreyashcode this issue has already been solved in the latest commit, I forgot to close this issue. We have other open issues as well, if interested you can have a try at them.

**Comment by devansh-299** [comment]
Already solved
