### ISSUE TITLE
Repository Singleton Pattern

### ISSUE THREAD

**Issue by unc0ded** [devansh-299/LunchBox#50]
### Description

While following MVVM architecture, it's recommended to have the Repository as a _Singleton_, which is not followed in this app yet (a new instance is created for every ViewModel instance, and in one of the ViewModels, even for every method in the ViewModel).
**Edit**: Since ApiService is already a singleton, this is now only a code style issue. Only a global Repository instance should exist in every Viewmodel.

**Comment by epicadk** [comment]
> ### Description
> While following MVVM architecture, it's recommended to have the Repository as a _Singleton_, which is not followed in this app yet (a new instance is created for every ViewModel instance, and in one of the ViewModels, even for every method in the ViewModel).


Yeah I had taken this up with @devansh-299 he said we'll have a different repo for each View Model

**Comment by devansh-299** [comment]
Singleton repository would have been beneficial with we were initializing, for our case `ApiManager` inside it. But as you can see we already have made `ApiManager` itself a singleton and the repository is just acting as a layer of abstraction over it, it doesn't make sense to repository again a singleton.

**Comment by unc0ded** [comment]
Hmm I see, but I think at least there should be some uniformity. Like in `SearchFragment`, a new instance is made for every method, while in `HomeFragment`, only one instance is used (globally).

**Comment by devansh-299** [comment]
@unc0ded I understand your concern. I too believe that there should be some form of uniformity in the code base and I think using the global instance approach should be followed. 
Do you want to work on this?

**Comment by unc0ded** [comment]
> @unc0ded I understand your concern. I too believe that there should be some form of uniformity in the code base and I think using the global instance approach should be followed.
> Do you want to work on this?

Yeah I'll do it. Thanks

**Comment by devansh-299** [comment]
> 
> 
> > @unc0ded I understand your concern. I too believe that there should be some form of uniformity in the code base and I think using the global instance approach should be followed.
> > Do you want to work on this?
> 
> Yeah I'll do it. Thanks

Also update the issue description accordingly

**Comment by unc0ded** [comment]
@devansh-299 
While I was cleaning up the `SearchViewModel`, I realised there is another `SearchFragmentViewModel` which has very similar contents, isn't used anywhere, and was created by you in the commit when you added the checkstyle plugin. Seems to me like this entire file is redundant. Any idea? Should I delete it?

**Comment by epicadk** [comment]
> @devansh-299
> While I was cleaning up the `SearchViewModel`, I realised there is another `SearchFragmentViewModel` which has very similar contents, isn't used anywhere, and was created by you in the commit when you added the checkstyle plugin. Seems to me like this entire file is redundant. Any idea? Should I delete it?

I deleted it in my PR.

**Comment by unc0ded** [comment]
> 
> I deleted it in my PR.

Cool
