### ISSUE TITLE
 Use the opaque uri

### ISSUE THREAD

**Issue by epicadk** [devansh-299/LunchBox#51]
### Description

Use the opaque uri mentioned in google maps doc [here](https://developers.google.com/maps/documentation/urls/android-intents)

**Comment by devansh-299** [comment]
@epicadk in our use cases why would non-opaque URIs present any issues? In my opinion, using opaque URIs in our case will be just a developer's preference without any gains.

**Comment by epicadk** [comment]
> @epicadk in our use cases why would non-opaque URIs present any issues? In my opinion, using opaque URIs in our case will be just a developer's preference without any gains.

@devansh-299 Actually the one that is present currently doesn't point to the restaurant but rather to the lat lon in the api (which is not exactly accurate) , this will ensure that the user sees exactly the restaurant and not any other point. I couldn't do this with the uri you used so I used the opaque uri.

**Comment by unc0ded** [comment]
> this will ensure that the user sees exactly the restaurant and not any other point.

@epicadk Is that because of the `q=%s` parameter?

**Comment by epicadk** [comment]
> > this will ensure that the user sees exactly the restaurant and not any other point.
> 
> @epicadk Is that because of the `q=%s` parameter?

Yeah I tried that with the url and it only takes either lat lon or string not both at the same time

**Comment by devansh-299** [comment]
> 
> 
> > @epicadk in our use cases why would non-opaque URIs present any issues? In my opinion, using opaque URIs in our case will be just a developer's preference without any gains.
> 
> @devansh-299 Actually the one that is present currently doesn't point to the restaurant but rather to the lat lon in the api (which is not exactly accurate) , this will ensure that the user sees exactly the restaurant and not any other point. I couldn't do this with the uri you used so I used the opaque uri.

Oh okay. Then I guess this is the way to go!
