### ISSUE TITLE
No results found on Application Launch. 

### ISSUE THREAD

**Issue by epicadk** [devansh-299/LunchBox#55]
### Description

There is a `No results found` toast when application is launched

### Expected Behavior
`No results should` only be displayed when user clicks on a filter

**Comment by unc0ded** [comment]
@devansh-299 
Since no one seems to be picking up these issues, I can take up 2-3 of these.

**Comment by devansh-299** [comment]
> 
> 
> @devansh-299
> Since no one seems to be picking up these issues, I can take up 2-3 of these.

Sure! go ahead
