### ISSUE TITLE
Unwanted back button in toolbar

### ISSUE THREAD

**Issue by unc0ded** [devansh-299/LunchBox#58]
### Description

- `SearchFragment` and `FoodFragment` show a back button in the toolbar, which is not desired, as they are top-level destinations.

### Screenshot/Recording

<img src="https://user-images.githubusercontent.com/56927116/97083437-a60ad800-162d-11eb-9eaf-474530a6d9b2.png" height="30%" width="30%"/> <img src="https://user-images.githubusercontent.com/56927116/97083438-a7d49b80-162d-11eb-86a3-2da1ea0b6c0c.png" height="30%" width="30%"/>

**Comment by epicadk** [comment]
@unc0ded can you use the html img tag with height and width attribute so that the image isn't too large?

**Comment by unc0ded** [comment]
I was actually looking for it, couldn't figure out initially if there was a way to scale it down rather than manually specifying height and width. I've updated it.

**Comment by epicadk** [comment]
btw yes this is a valid issue that @devansh-299 had pointed out in the meeting.

**Comment by unc0ded** [comment]
@devansh-299 
I'll take this one up too.

**Comment by epicadk** [comment]
> @devansh-299
> I'll take this one up too.

Are you stiill working on this @unc0ded

**Comment by unc0ded** [comment]
@epicadk 
Oh I forgot about it, will do it in a few hours time.

**Comment by unc0ded** [comment]
@epicadk I'm closing this one, as @devansh-299 has changed the UI completely and this is no longer an issue.
